image: Visual Studio 2019

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest --output-on-failure