language: cpp

dist: bionic

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

matrix:
  include:
    - env: BUILD_CONFIGURATION=Debug SAN=ASAN
      os: linux
      compiler: clang
    - env: BUILD_CONFIGURATION=Debug SAN=MSAN
      os: linux
      compiler: clang
    - env: BUILD_CONFIGURATION=Release SAN=ASAN
      os: linux
      compiler: clang
    - env: BUILD_CONFIGURATION=Release SAN=MSAN
      os: linux
      compiler: clang
      
    # Windows
    - os: windows
      env:
      - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DSAN=$SAN
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email: false